name: vue-ts-cli

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: get registry
      run: npm config set registry https://registry.npm.taobao.org
    - name: install deps
      run: npm install
    - name: build app
      run: npm run build
    - name: copy dist file with scp
      uses: appleboy/scp-action@master
      with:
         host: ''
